name: Deploy to an AWS S3 Bucket

on: workflow_dispatch

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Minify html, css and js files
        uses: pabcrudel/static-site-optimizer@main
        with:
          project_path: website

      - name: Rsync
        run: rsync -av -e "ssh -i ${{ secrets.AWS_KEY }}" website/ ec2-user@54.92.215.93:/var/www/html/