name: Deploy to Azure Apache

on: workflow_dispatch

jobs:
  rsync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Action - rsync
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          TARGET: ${{ secrets.APACHE_TARGET }}
          ARGS: -avz --delete --exclude=/.git/ --exclude=/.github/ --no-perms --no-times
          SOURCE: website/
