name: Deploy to Azure Apache

on: workflow_dispatch

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        
      - name: Action - rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          KEY: ${{ secrets.KEY }}
          TARGET: ${{ secrets.APACHE_TARGET }}
          SOURCE: website
